#pragma once
/**
 * @file exchange/orderbook/Order.hpp
 * @brief Complete order data structures for the limit order book.
 *
 * Design decisions
 * ────────────────
 * • Orders are plain POD-like structs stored by value inside the book's
 *   price-level containers — no heap per order on the hot path.
 * • A single Order struct covers all types; discriminated by OrderType.
 * • Queue position is tracked via sequence number (seqNo) for FIFO priority.
 * • All mutation happens through the OrderBook API — Order itself is dumb data.
 */

#include "core/Types.hpp"
#include <string>

namespace qtl {

// ─────────────────────────────────────────────────────────────
// Order — the universal order record
// ─────────────────────────────────────────────────────────────

struct Order {
    // Identity
    OrderId     id{0};
    Symbol      symbol;
    std::string strategyId;

    // Specification
    Side        side{Side::Buy};
    OrderType   type{OrderType::Limit};
    Price       price{0.0};       ///< Limit price; 0 for market orders
    Quantity    quantity{0};
    TimeInForce tif{TimeInForce::GTC};

    // State
    Quantity    filledQty{0};
    OrderStatus status{OrderStatus::New};

    // Timing & queue position
    Timestamp   createdAt{0};     ///< ns epoch — set by OrderBook::addOrder
    uint64_t    seqNo{0};         ///< Monotonic sequence; determines FIFO priority

    // ── Derived queries ─────────────────────────────────────
    [[nodiscard]] Quantity remainingQty() const noexcept { return quantity - filledQty; }
    [[nodiscard]] bool isActive()  const noexcept {
        return status == OrderStatus::New || status == OrderStatus::PartiallyFilled;
    }
    [[nodiscard]] bool isLimit()   const noexcept { return type == OrderType::Limit;  }
    [[nodiscard]] bool isMarket()  const noexcept { return type == OrderType::Market; }
    [[nodiscard]] bool isBuy()     const noexcept { return side == Side::Buy;  }
    [[nodiscard]] bool isSell()    const noexcept { return side == Side::Sell; }
};

// ─────────────────────────────────────────────────────────────
// TradeReport — one fill generated by the matching engine
// ─────────────────────────────────────────────────────────────

struct TradeReport {
    TradeId   tradeId;
    Symbol    symbol;
    Price     price;
    Quantity  quantity;
    OrderId   makerOrderId;      ///< Passive (resting) side
    OrderId   takerOrderId;      ///< Aggressive (incoming) side
    Side      takerSide;
    Timestamp timestamp;
    int64_t   matchLatencyNs{0}; ///< Arrival → trade, nanoseconds
};

// ─────────────────────────────────────────────────────────────
// ModifyRequest — payload for modifyOrder()
// ─────────────────────────────────────────────────────────────

struct ModifyRequest {
    OrderId  orderId;
    Price    newPrice{0.0};    ///< 0 = keep existing
    Quantity newQuantity{0};   ///< 0 = keep existing
};

} // namespace qtl
