#pragma once
/**
 * @file core/Types.hpp
 * @brief Fundamental type aliases and enumerations used project-wide.
 *
 * Centralising primitive typedefs here allows us to:
 *  - switch underlying numeric types in one place (e.g. int64→int128 price)
 *  - enforce semantic clarity (Price is not just a double)
 *  - avoid accidental implicit conversions between domain concepts
 */

#include <cstdint>
#include <string>
#include <chrono>

namespace qtl {

// ─────────────────────────────────────────────────────────────
// Primitive domain aliases
// ─────────────────────────────────────────────────────────────

/// Price stored as double; production systems often use fixed-point int64.
using Price    = double;

/// Quantity of shares / contracts (signed so short positions are negative).
using Quantity = int64_t;

/// Order / trade / event identifier.
using OrderId  = uint64_t;
using TradeId  = uint64_t;

/// Human-readable instrument ticker, e.g. "AAPL", "SPX".
using Symbol   = std::string;

/// Nanosecond epoch timestamp (wall-clock or simulated).
using Timestamp = int64_t;

// ─────────────────────────────────────────────────────────────
// Enumerations
// ─────────────────────────────────────────────────────────────

/// Order direction.
enum class Side : uint8_t {
    Buy  = 0,
    Sell = 1
};

/// Order type classifications.
enum class OrderType : uint8_t {
    Market,
    Limit,
    StopLimit,
    IOC,    ///< Immediate-Or-Cancel
    FOK     ///< Fill-Or-Kill
};

/// Lifecycle status of a single order.
enum class OrderStatus : uint8_t {
    New,
    PartiallyFilled,
    Filled,
    Cancelled,
    Rejected,
    PendingCancel
};

/// Time-in-force semantics.
enum class TimeInForce : uint8_t {
    GTC,   ///< Good-Till-Cancelled
    GTD,   ///< Good-Till-Date
    DAY,
    IOC,
    FOK
};

/// Option contract flavour.
enum class OptionType : uint8_t {
    Call,
    Put
};

/// Direction of an event flowing through the system.
enum class EventType : uint8_t {
    Market,   ///< Tick / quote / book update from feed
    Order,    ///< New/cancel/modify order submitted by strategy
    Fill,     ///< Execution report from matching engine
    Signal,   ///< Alpha signal generated by strategy
    Risk,     ///< Risk breach notification
    Timer,    ///< Scheduled timer event
    System    ///< System-level lifecycle events
};

// ─────────────────────────────────────────────────────────────
// Utility: current nanosecond timestamp
// ─────────────────────────────────────────────────────────────
inline Timestamp nowNs() noexcept {
    return std::chrono::duration_cast<std::chrono::nanoseconds>(
               std::chrono::high_resolution_clock::now().time_since_epoch())
        .count();
}

} // namespace qtl
