#pragma once
/**
 * @file portfolio/positions/PositionManager.hpp
 * @brief Multi-symbol, multi-strategy position tracking.
 *
 * Architecture
 * ────────────
 * Maintains a Position record per (symbol × strategy) pair.
 * Aggregated queries collapse across strategies for a symbol-level
 * or portfolio-level view.
 *
 * Position lifecycle
 * ──────────────────
 *   Flat → Long  : first buy fill
 *   Flat → Short : first sell fill (if short selling allowed)
 *   Long → Flat  : sell fill that exhausts long qty
 *   Long → Short : sell fill that crosses flat (increases short)
 *   Short → Flat : buy fill that exhausts short
 *
 * Cost basis methods supported
 * ────────────────────────────
 *   FIFO  — First-In-First-Out (default, regulatory standard)
 *   VWAP  — Volume-Weighted Average Price (simplified, fast)
 *
 * Thread safety
 * ─────────────
 * All public methods guarded by shared_mutex.
 * onFill() takes exclusive lock; queries take shared lock.
 */

#include "core/Types.hpp"
#include <mutex>
#include <shared_mutex>
#include <unordered_map>
#include <string>
#include <vector>
#include <deque>
#include <shared_mutex>
#include <sstream>
#include <iomanip>
#include <cmath>
#include <stdexcept>
#include <algorithm>

namespace qtl {

// ─────────────────────────────────────────────────────────────
// Lot — one FIFO lot (a single fill that opened or added to a position)
// ─────────────────────────────────────────────────────────────

struct Lot {
    Quantity quantity{0};    ///< Remaining qty in this lot
    Price    entryPrice{0.0};
    Timestamp entryTime{0};
    std::string strategyId;
};

// ─────────────────────────────────────────────────────────────
// Position — state for one (symbol × strategy) pair
// ─────────────────────────────────────────────────────────────

struct Position {
    Symbol      symbol;
    std::string strategyId;

    // Current state
    Quantity    netQty{0};           ///< +long, -short, 0=flat
    double      avgEntryPrice{0.0};  ///< VWAP cost basis
    Price       lastPrice{0.0};      ///< Last mark price

    // Cumulative
    double      realisedPnl{0.0};
    double      totalCommission{0.0};
    uint64_t    fillCount{0};
    Quantity    totalBought{0};
    Quantity    totalSold{0};

    // FIFO lots for realised P&L calculation
    std::deque<Lot> lots;

    // ── Derived queries ──────────────────────────────────────
    [[nodiscard]] bool     isFlat()  const noexcept { return netQty == 0;  }
    [[nodiscard]] bool     isLong()  const noexcept { return netQty >  0;  }
    [[nodiscard]] bool     isShort() const noexcept { return netQty <  0;  }
    [[nodiscard]] Quantity absQty()  const noexcept { return std::abs(netQty); }

    [[nodiscard]] double unrealisedPnl() const noexcept {
        if (netQty == 0 || lastPrice <= 0 || avgEntryPrice <= 0) return 0.0;
        return (lastPrice - avgEntryPrice) * static_cast<double>(netQty);
    }

    [[nodiscard]] double totalPnl() const noexcept {
        return realisedPnl + unrealisedPnl();
    }

    [[nodiscard]] double marketValue() const noexcept {
        return lastPrice * static_cast<double>(netQty);
    }

    [[nodiscard]] double costBasis() const noexcept {
        return avgEntryPrice * static_cast<double>(std::abs(netQty));
    }

    [[nodiscard]] double returnPct() const noexcept {
        if (costBasis() == 0) return 0.0;
        return unrealisedPnl() / costBasis() * 100.0;
    }
};

// ─────────────────────────────────────────────────────────────
// PositionManager
// ─────────────────────────────────────────────────────────────

class PositionManager {
public:
    explicit PositionManager(bool allowShortSelling = true)
        : allowShort_{allowShortSelling} {}

    // ── Fill processing ───────────────────────────────────────

    /**
     * @brief Process a fill and update positions.
     *
     * @param symbol      Instrument
     * @param side        Buy / Sell
     * @param fillPrice   Execution price
     * @param fillQty     Quantity filled (positive)
     * @param commission  Brokerage cost
     * @param strategyId  Attribution tag (empty = aggregate)
     * @return Realised P&L generated by this fill (0 if opening a position)
     */
    double onFill(const Symbol& symbol,
                  Side          side,
                  Price         fillPrice,
                  Quantity      fillQty,
                  double        commission  = 0.0,
                  const std::string& strategyId = "") {
        if (fillQty <= 0 || fillPrice <= 0) return 0.0;

        std::unique_lock lock{mutex_};
        auto& pos = getOrCreate(symbol, strategyId);

        pos.fillCount++;
        pos.totalCommission += commission;

        double realisedPnl = 0.0;

        if (side == Side::Buy) {
            pos.totalBought += fillQty;
            realisedPnl = processBuy(pos, fillPrice, fillQty, commission);
        } else {
            pos.totalSold += fillQty;
            realisedPnl = processSell(pos, fillPrice, fillQty, commission);
        }

        pos.realisedPnl += realisedPnl;
        totalRealisedPnl_ += realisedPnl;
        return realisedPnl;
    }

    /**
     * @brief Update mark price for MTM calculation.
     */
    void mark(const Symbol& symbol, Price price,
              const std::string& strategyId = "") {
        std::unique_lock lock{mutex_};
        if (strategyId.empty()) {
            // Update all strategies for this symbol
            for (auto& [key, pos] : positions_) {
                if (pos.symbol == symbol) pos.lastPrice = price;
            }
        } else {
            auto it = positions_.find(makeKey(symbol, strategyId));
            if (it != positions_.end()) it->second.lastPrice = price;
        }
    }

    // ── Queries ───────────────────────────────────────────────

    /**
     * @brief Get position for a specific (symbol × strategy).
     * Returns default Position if not found.
     */
    [[nodiscard]] Position getPosition(const Symbol& sym,
                                        const std::string& strat = "") const {
        std::shared_lock lock{mutex_};
        auto it = positions_.find(makeKey(sym, strat));
        return it == positions_.end() ? Position{} : it->second;
    }

    /**
     * @brief Net quantity across all strategies for a symbol.
     */
    [[nodiscard]] Quantity netQty(const Symbol& sym) const {
        std::shared_lock lock{mutex_};
        Quantity total = 0;
        for (auto& [key, pos] : positions_) {
            if (pos.symbol == sym) total += pos.netQty;
        }
        return total;
    }

    /**
     * @brief Total unrealised P&L across all positions.
     */
    [[nodiscard]] double totalUnrealisedPnl() const {
        std::shared_lock lock{mutex_};
        double total = 0;
        for (auto& [key, pos] : positions_) total += pos.unrealisedPnl();
        return total;
    }

    /**
     * @brief Total realised P&L across all positions.
     */
    [[nodiscard]] double totalRealisedPnl() const noexcept {
        return totalRealisedPnl_;
    }

    /**
     * @brief Total P&L = realised + unrealised.
     */
    [[nodiscard]] double totalPnl() const {
        return totalRealisedPnl_ + totalUnrealisedPnl();
    }

    /**
     * @brief Total market value of all positions (long - short in $).
     */
    [[nodiscard]] double totalMarketValue() const {
        std::shared_lock lock{mutex_};
        double total = 0;
        for (auto& [key, pos] : positions_) total += pos.marketValue();
        return total;
    }

    /**
     * @brief All open positions (non-flat).
     */
    [[nodiscard]] std::vector<Position> openPositions() const {
        std::shared_lock lock{mutex_};
        std::vector<Position> out;
        for (auto& [key, pos] : positions_) {
            if (!pos.isFlat()) out.push_back(pos);
        }
        return out;
    }

    /**
     * @brief All tracked symbols (including flat).
     */
    [[nodiscard]] std::vector<Symbol> allSymbols() const {
        std::shared_lock lock{mutex_};
        std::vector<Symbol> syms;
        for (auto& [key, pos] : positions_) {
            if (std::find(syms.begin(), syms.end(), pos.symbol) == syms.end())
                syms.push_back(pos.symbol);
        }
        return syms;
    }

    [[nodiscard]] size_t positionCount() const {
        std::shared_lock lock{mutex_};
        return positions_.size();
    }

    [[nodiscard]] size_t openPositionCount() const {
        std::shared_lock lock{mutex_};
        size_t n = 0;
        for (auto& [key, pos] : positions_) if (!pos.isFlat()) ++n;
        return n;
    }

    /**
     * @brief Format a position table for display.
     */
    [[nodiscard]] std::string printPositions() const {
        std::shared_lock lock{mutex_};
        std::ostringstream oss;
        oss << std::fixed << std::setprecision(2);
        oss << "+──────────+──────────+──────────+──────────+──────────+──────────+\n";
        oss << "| Symbol   | NetQty   | AvgEntry | LastPx   | Unreal$  | Real$    |\n";
        oss << "+──────────+──────────+──────────+──────────+──────────+──────────+\n";
        for (auto& [key, pos] : positions_) {
            if (pos.isFlat()) continue;
            oss << "| " << std::setw(8) << std::left  << pos.symbol
                << " | " << std::setw(8) << std::right << pos.netQty
                << " | " << std::setw(8) << pos.avgEntryPrice
                << " | " << std::setw(8) << pos.lastPrice
                << " | " << std::setw(8) << pos.unrealisedPnl()
                << " | " << std::setw(8) << pos.realisedPnl << " |\n";
        }
        oss << "+──────────+──────────+──────────+──────────+──────────+──────────+\n";
        oss << "  Total Realised: $" << totalRealisedPnl_
            << "  Total Unrealised: $" << totalUnrealisedPnl() << "\n";
        return oss.str();
    }

    void reset() {
        std::unique_lock lock{mutex_};
        positions_.clear();
        totalRealisedPnl_ = 0.0;
    }

private:
    static std::string makeKey(const Symbol& sym, const std::string& strat) {
        return sym + (strat.empty() ? "" : ":" + strat);
    }

    Position& getOrCreate(const Symbol& sym, const std::string& strat) {
        auto key = makeKey(sym, strat);
        auto it  = positions_.find(key);
        if (it == positions_.end()) {
            Position p;
            p.symbol     = sym;
            p.strategyId = strat;
            positions_[key] = p;
            return positions_[key];
        }
        return it->second;
    }

    // ── FIFO P&L calculation helpers ─────────────────────────

    double processBuy(Position& pos, Price price, Quantity qty,
                       double /*commission*/) {
        double realised = 0.0;

        if (pos.isShort()) {
            // Covering short: realised P&L = (entry_price - cover_price) × qty
            Quantity cover = std::min(qty, -pos.netQty);
            qty -= cover;
            // Consume lots FIFO
            realised += consumeLots(pos, price, cover, /*coveringShort=*/true);
        }

        // Remaining qty opens / adds to long
        if (qty > 0) {
            pos.netQty += qty;
            updateVwap(pos, price, qty, Side::Buy);
            pos.lots.push_back({qty, price, nowNs(), pos.strategyId});
        }

        return realised;
    }

    double processSell(Position& pos, Price price, Quantity qty,
                        double /*commission*/) {
        double realised = 0.0;

        if (pos.isLong()) {
            // Closing long: realised P&L = (sell_price - entry_price) × qty
            Quantity close = std::min(qty, pos.netQty);
            qty -= close;
            realised += consumeLots(pos, price, close, /*coveringShort=*/false);
        }

        // Remaining qty opens / adds to short
        if (qty > 0 && allowShort_) {
            pos.netQty -= qty;
            updateVwap(pos, price, qty, Side::Sell);
            pos.lots.push_back({-qty, price, nowNs(), pos.strategyId});
        }

        return realised;
    }

    // Consume FIFO lots, return realised P&L
    double consumeLots(Position& pos, Price closePrice,
                        Quantity qty, bool coveringShort) {
        double realised = 0.0;
        while (qty > 0 && !pos.lots.empty()) {
            Lot& lot = pos.lots.front();
            Quantity lotQty = std::abs(lot.quantity);
            Quantity take   = std::min(qty, lotQty);

            if (coveringShort) {
                // Buying to cover short lot (lot.quantity < 0)
                realised += (lot.entryPrice - closePrice) *
                            static_cast<double>(take);
            } else {
                // Selling to close long lot (lot.quantity > 0)
                realised += (closePrice - lot.entryPrice) *
                            static_cast<double>(take);
            }

            lot.quantity += coveringShort ? take : -take;
            if (coveringShort) pos.netQty += take;
            else               pos.netQty -= take;
            qty -= take;

            if (std::abs(lot.quantity) == 0) pos.lots.pop_front();
        }
        return realised;
    }

    void updateVwap(Position& pos, Price price, Quantity qty, Side side) {
        Quantity prevAbs = std::abs(pos.netQty) - (side == Side::Buy ? qty : -qty);
        if (prevAbs < 0) prevAbs = 0;
        Quantity newAbs  = std::abs(pos.netQty);
        if (newAbs <= 0) { pos.avgEntryPrice = 0; return; }
        pos.avgEntryPrice = (pos.avgEntryPrice * prevAbs +
                             price * qty) /
                            static_cast<double>(newAbs);
    }

    bool allowShort_;
    mutable std::shared_mutex mutex_;
    std::unordered_map<std::string, Position> positions_;
    double totalRealisedPnl_{0.0};
};

} // namespace qtl
